#!/bin/zsh

# Load the oh-my-zsh's library
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh)
antigen bundle git
# antigen bundle pip
antigen bundle command-not-found
antigen bundle docker

# Syntax highlighting bundle
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle ael-code/zsh-colored-man-pages

# Load the theme
antigen theme romkatv/powerlevel10k

# Tell Antigen that you're done
antigen apply
